apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router-web
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: "bootcamp-static-ip"
spec:
  rules:
    - host: example.placeholder
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: web-frontend
                port:
                  number: 8080
